### ISSUE TITLE
3.07.1 has no entries in Delphinus for Tokyo

### ISSUE THREAD

**Issue by Memnarch** [gabr42/OmniThreadLibrary#99]
Hi,
Just noticed, that the Delphinus.Info and Delphinus.Installation are missing the supported Compilerversion and packages for Tokyo

**Comment by gabr42** [comment]
Ooops!

Fixed, thanks for the info.

**Comment by Memnarch** [comment]
Keep in mind that the current release is still missing these infos :P

**Comment by gabr42** [comment]
Yep, I'll update the 'release-3.07.1' tag.

**Comment by gabr42** [comment]
Release recreated ...

**Comment by Memnarch** [comment]
and now you used - instead of dots which will confuse Delphinus(it'll recognize it as unstable) and invalidates the URL linked in your Blogpost :P
https://github.com/gabr42/OmniThreadLibrary/tree/release-3.07.1 (original expected one
https://github.com/gabr42/OmniThreadLibrary/tree/release-3.07-1 (current one)

**Comment by gabr42** [comment]
Damn! Recreated again.
